Ponder.registry((event) => {
	event.create('#minecraft:flowers') // 填入需要添加 Ponder 的 Item/Tag, 填入多个时要用 [ ] 包裹
		.scene(
			"kubejs:flowers", // Ponder ID
			"原木", // 侧边显示的标题
            "kubejs:flowers",
			(scene) => {
scene.idleSeconds(0.5)
scene.showBasePlate()
scene.idleSeconds(1)
scene.world.showSection([3, 1, 3], Direction.DOWN)
scene.idleSeconds(0.5)
scene.world.showSection([2, 1, 3], Direction.DOWN)
scene.idleSeconds(0.5)
scene.world.showSection([2, 1, 2], Direction.DOWN)
scene.idleSeconds(0.5)
scene.world.showSection([3, 1, 2], Direction.DOWN)
scene.idleSeconds(0.5)
scene.world.showSection([3, 2, 3], Direction.DOWN)
scene.idleSeconds(0.5)
scene.world.showSection([2, 2, 3], Direction.DOWN)
scene.idleSeconds(0.5)
scene.world.showSection([2, 2, 2], Direction.DOWN)
scene.idleSeconds(0.5)
scene.world.showSection([3, 2, 2], Direction.DOWN)
scene.idleSeconds(1)

scene.addKeyframe()
scene.text(40, "一花一树一世界,各种各样的花朵点缀着主世界", [3, 2, 3])
scene.idleSeconds(3)
scene.text(40, "大多数花会天然在一些生物群系的泥土和草方块上生成", [3, 2, 3])
scene.idleSeconds(3)
scene.text(40, "即使是在被积雪的生物群系，相邻的泥土方块覆盖着雪，花仍会天然生成在泥土和草方块上")
scene.idleSeconds(3)

scene.addKeyframe()
scene.idleSeconds(1)
scene.world.showSection([0, 1, 1, 5 ,1, 0], Direction.DOWN)
scene.world.showSection([0, 1, 2, 1 ,1, 5], Direction.DOWN)
scene.world.showSection([2, 1, 5, 5 ,1, 4], Direction.DOWN)
scene.world.showSection([4, 1, 2, 5 ,1, 3], Direction.DOWN)
scene.idleSeconds(1)
scene.showControls(30, [3, 2, 3], "left")
	.rightClick() 
	.withItem("minecraft:bone_meal")
scene.idleSeconds(1)
scene.world.showSection([0, 2, 0, 5 ,6, 5], Direction.WEST)
scene.idleSeconds(1)
scene.text(50, "对草方块使用骨粉后,花有1⁄8的概率代替矮草丛生成。能生成的花取决于生成位置所在的生物群系")
scene.idleSeconds(4)
scene.text(40, "除了小花以外,还有各种各样的大型花")
scene.idleSeconds(3)

scene.addKeyframe()
scene.showControls(30, [1, 3, 4], "left")
	.rightClick() 
	.withItem("minecraft:bone_meal")
scene.idleSeconds(1)
scene.world.createItemEntity([1, 3, 4], Direction.WEST, 'minecraft:lilac')
scene.idleSeconds(1)
scene.text(40, "对着大型花(瓶子草除外)使用骨粉时,它会掉落1株新的对应花种", [1, 3, 4])
scene.idleSeconds(3)
scene.text(50, "所有的花均能直接合成出染料,染料的颜色一般与花本身的颜色相近。小型花可以合成出1个染料,大型花可以合成出2个染料")
scene.idleSeconds(3)
            }
		)
})